# Generated by Django 3.2.8 on 2021-11-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_', '0003_auto_20211114_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
