# Generated by Django 3.2.8 on 2021-11-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_', '0004_post_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
    ]
